
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:17 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Linux - 6.15.3-zen1-1-zen - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /opt/microchip/xc32/v4.60/bin/xc32-gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Warning: dinit optimization threshholds not set; dinit may not function
      /opt/microchip/xc32/v4.60/bin/bin/gcc/pic32mx/8.3.1/../../../../bin/pic32m-ld: warning: cannot find entry symbol _reset; defaulting to 000000009d000000
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/xDNA/Archives/Documents/MPLABX/GameCat_R4_VSC/_build/GameCat_R4/MPLAB/CMakeFiles/3.28.1/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /opt/microchip/xc32/v4.60/bin/xc32-g++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Warning: dinit optimization threshholds not set; dinit may not function
      /opt/microchip/xc32/v4.60/bin/bin/gcc/pic32mx/8.3.1/../../../../bin/pic32m-ld: warning: cannot find entry symbol _reset; defaulting to 000000009d000000
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/xDNA/Archives/Documents/MPLABX/GameCat_R4_VSC/_build/GameCat_R4/MPLAB/CMakeFiles/3.28.1/CompilerIdCXX/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1131 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      pic32m-gcc (Microchip XC32 Compiler v4.60) 8.3.1 Build date: Feb 19 2025
      Copyright (C) 2018 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
...
