
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:17 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Linux - 6.15.3-zen1-1-zen - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /opt/microchip/xc32/v4.60/bin/xc32-gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      cc1: fatal error: CMakeCCompilerId.c: No such file or directory
      compilation terminated.
      
      

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:17 (project)"
    message: |
      The target system is: Generic -  - 
      The host system is: Linux - 6.15.3-zen1-1-zen - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /opt/microchip/xc32/v4.60/bin/xc32-gcc 
      Build flags: 
      Id flags: -c 
      
      The output was:
      1
      shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
      pic32m-gcc: error: CMakeCCompilerId.c: No such file or directory
      pic32m-gcc: fatal error: no input files
      compilation terminated.
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /opt/microchip/xc32/v4.60/bin/xc32-gcc 
      Build flags: 
      Id flags: -Aa 
      
      The output was:
      1
      <command-line>: error: missing '(' after predicate
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /opt/microchip/xc32/v4.60/bin/xc32-gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      shell-init: error al obtener el directorio actual: getcwd: no se puede acceder a los directorios padre: No existe el fichero o el directorio
      /opt/microchip/xc32/v4.60/bin/bin/gcc/pic32mx/8.3.1/../../../../bin/pic32m-ld: cannot open output file a.out: No existe el fichero o el directorio
      collect2: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /opt/microchip/xc32/v4.60/bin/xc32-gcc 
      Build flags: 
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      1
      shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
      shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
      /opt/microchip/xc32/v4.60/bin/bin/gcc/pic32mx/8.3.1/../../../../bin/pic32m-ld: cannot open output file a.out: No such file or directory
      collect2: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /opt/microchip/xc32/v4.60/bin/xc32-gcc 
      Build flags: 
      Id flags: -c 
      
      The output was:
      1
      Assembler messages:
      Fatal error: can't create CMakeCCompilerId.o: No existe el fichero o el directorio
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /opt/microchip/xc32/v4.60/bin/xc32-gcc 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      1
      pic32m-gcc: error: CMakeCCompilerId.c: No such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /opt/microchip/xc32/v4.60/bin/xc32-gcc 
      Build flags: 
      Id flags: -Aa 
      
      The output was:
      1
      <command-line>: error: missing '(' after predicate
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /opt/microchip/xc32/v4.60/bin/xc32-gcc 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      1
      Assembler messages:
      Fatal error: can't create CMakeCCompilerId.o: No such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /opt/microchip/xc32/v4.60/bin/xc32-gcc 
      Build flags: 
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      1
      cc1: fatal error: CMakeCCompilerId.c: No such file or directory
      compilation terminated.
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /opt/microchip/xc32/v4.60/bin/xc32-gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Warning: dinit optimization threshholds not set; dinit may not function
      /opt/microchip/xc32/v4.60/bin/bin/gcc/pic32mx/8.3.1/../../../../bin/pic32m-ld: warning: cannot find entry symbol _reset; defaulting to 000000009d000000
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/xDNA/Archives/Documents/MPLABX/GAME_CAT_R4_VSC/_build/GameCat_R4/MPLAB/CMakeFiles/3.28.1/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /opt/microchip/xc32/v4.60/bin/xc32-gcc 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      1
      cc1: warning: command line option '-ftarget=arm-arm-none-eabi' is valid for Java but not for C
      <built-in>: warning: ISO C99 requires whitespace after the macro name
      Error: unknown processor CORTEX-M3
      cc1: warning: command line option '-ftarget=arm-arm-none-eabi' is valid for Java but not for C
      <built-in>: warning: missing whitespace after the macro name
      In file included from /opt/microchip/xc32/v4.60/bin/bin/../../lib/gcc/pic32mx/8.3.1/../../../../pic32mx/lib/./crt0.S:50:
      /opt/microchip/xc32/v4.60/pic32mx/include/xc.h:724:4: error: #error Unknown processor!
       #  error Unknown processor!
          ^~~~~
      /opt/microchip/xc32/v4.60/bin/bin/../../lib/gcc/pic32mx/8.3.1/../../../../pic32mx/lib/./crt0.S:69:6: warning: #warning PIC32_SRS_SET_COUNT not defined on build line [-Wcpp]
       #    warning PIC32_SRS_SET_COUNT not defined on build line
            ^~~~~~~
      cc1: warning: command line option '-ftarget=arm-arm-none-eabi' is valid for Java but not for C
      cc1: fatal error: ./proc/cortex-m3/pcortex-m3.S: No such file or directory
      compilation terminated.
      cc1: warning: command line option '-ftarget=arm-arm-none-eabi' is valid for Java but not for C
      cc1: fatal error: ./proc/cortex-m3/pcortex-m3_div.S: No such file or directory
      compilation terminated.
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /opt/microchip/xc32/v4.60/bin/xc32-g++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Warning: dinit optimization threshholds not set; dinit may not function
      /opt/microchip/xc32/v4.60/bin/bin/gcc/pic32mx/8.3.1/../../../../bin/pic32m-ld: warning: cannot find entry symbol _reset; defaulting to 000000009d000000
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/xDNA/Archives/Documents/MPLABX/GAME_CAT_R4_VSC/_build/GameCat_R4/MPLAB/CMakeFiles/3.28.1/CompilerIdCXX/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1131 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      pic32m-gcc (Microchip XC32 Compiler v4.60) 8.3.1 Build date: Feb 19 2025
      Copyright (C) 2018 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
  -
    kind: "message-v1"
    backtrace:
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/opt/STMicroelectronics/STM32CubeCLT/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:17 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /opt/microchip/xc32/v4.60/bin/xc32-gcc 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is GNU, found in:
        /home/xDNA/Archives/Documents/MPLABX/GAME_CAT_R4_VSC/_build/GameCat_R4/MPLAB/CMakeFiles/3.28.1/CompilerIdC/CMakeCCompilerId.o
      
...
...
